package semantic.error;

public enum ErrorType {
    ID_NOT_DEFINED, ILLEGAL_TYPE_OF_VOID, MISMATCHED_NUMBER_OF_ARGUMENTS, NO_WHILE_FOR_CONTINUE, MAIN_NOT_FOUND,
    NO_WHILE_OR_SWITCH_FOR_BREAK, TYPE_MISMATCH;
}